---
defaults:
  mail:
    gid: 5000
    homedir: /var/vmail
    maildir: /var/vmail/%d/%a
    uid: 5000
  web:
    allow_override: All
    ip_map:
      1.2.3.4: 5.6.7.8
    ruby: y
    suexec: y
    traffic_quota_lock: n
    stats_type: webalizer
  users:
    userdir: /var/www/clients/client%c/web%a
    webuserdir: /var/www/clients/client%c/%a/web_user/%a
server:
  mail: 1.2.3.4
  web: 1.2.3.4
  db: 1.2.3.4
plesk:
  db: psa
  host: 127.0.0.1
  port: 3306
  user: pleskuser
  pass: pleskpass
  sync:
    host: 127.0.0.1
    user: root
    port: 22
ispconfig:
  uri: http://localhost:8079/remote/
  proxy: http://localhost:8079/remote/index.php
  user: apiuser
  pass: 123456
postscript: execute_me_later.sh
mailsync:
  writerc: migration_offlineimap.rc
  fromserver: mail.%d
  use_ssl: 1
